# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.2.0
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify min OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: '10.0.22000'
  resources:
  ###########################
  # Modify windows settings #
  ###########################
    - resource: Microsoft.Windows.Developer/Taskbar
      directives:
        description: Modify taskbar settings
        allowPrerelease: true
      settings:
        Alignment: KeepCurrentValue # [KeepCurrentValue, Left, Middle]
        HideLabelsMode: Always # [KeepCurrentValue, Never, WhenFull, Always]
        SearchBoxMode: Hide # [KeepCurrentValue, ShowIconAndLabel, ShowIconOnly, SearchBox, Hide]
        TaskViewButton: Hide # [KeepCurrentValue, Show, Hide]
        WidgetsButton: Hide # [KeepCurrentValue, Show, Hide]
        RestartExplorer: True # Use caution when setting `RestartExplorer: true` as this will force explorer to close. Required for `HideLabelsMode`.
    - resource: Microsoft.Windows.Developer/WindowsExplorer
      directives:
        description: Modify File Explorer settings
        allowPrerelease: true
      settings:
        FileExtensions: Hide # [KeepCurrentValue, Show, Hide]
        HiddenFiles: Hide # [KeepCurrentValue, Show, Hide]
        ItemCheckBoxes: Hide # [KeepCurrentValue, Show, Hide]
        RestartExplorer: True # Use caution when setting `RestartExplorer: true` as this will force explorer to close. Required for all WindowsExplorer settings.
    - resource: Microsoft.Windows.Developer/EnableDarkMode
      directives:
        description: Enable dark mode
        allowPrerelease: true
      settings:
        Ensure: Present # [Present, Absent]
        RestartExplorer: true # Use caution when setting `RestartExplorer: true` as this will force explorer to close. Required to apply changes
  ##########################
  # Uninstall default apps #
  ##########################
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Clipchamp
      directives:
        description: Remove Microsoft Clipchamp
        allowPrerelease: true
      settings:
        id: 9P1J8S7CCWWT
        source: msstore
        ensure: absent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: FeedbackHub
      directives:
        description: Remove Feedback Hub
        allowPrerelease: true
      settings:
        id: 9NBLGGH4R32N
        source: msstore
        ensure: absent
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: WindowsCamera
      directives:
        description: Remove Windows Camera
        allowPrerelease: true
      settings:
        id: 9WZDNCRFJBBG
        source: msstore
        ensure: absent
  ################
  # Install apps #
  ################
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Ghisler.TotalCommander
      directives:
        description: Install Ghisler.TotalCommander
        allowPrerelease: true
      settings:
        id: Ghisler.TotalCommander
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Google.Chrome
      directives:
        description: Install Google.Chrome
        allowPrerelease: true
      settings:
        id: Google.Chrome
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Gyan.FFmpeg
      directives:
        description: Install Gyan.FFmpeg
        allowPrerelease: true
      settings:
        id: Gyan.FFmpeg
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Logitech.OptionsPlus
      directives:
        description: Install Logitech.OptionsPlus
        allowPrerelease: true
      settings:
        id: Logitech.OptionsPlus
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Microsoft.PowerShell
      directives:
        description: Install Microsoft.PowerShell
        allowPrerelease: true
      settings:
        id: Microsoft.PowerShell
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: TorProject.TorBrowser
      directives:
        description: Install TorProject.TorBrowser
        allowPrerelease: true
      settings:
        id: TorProject.TorBrowser
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: UCBerkeley.BOINC
      directives:
        description: Install UCBerkeley.BOINC
        allowPrerelease: true
      settings:
        id: UCBerkeley.BOINC
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: VideoLAN.VLC
      directives:
        description: Install VideoLAN.VLC
        allowPrerelease: true
      settings:
        id: VideoLAN.VLC
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: WireGuard.WireGuard
      directives:
        description: Install WireGuard.WireGuard
        allowPrerelease: true
      settings:
        id: WireGuard.WireGuard
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: XnSoft.XnViewMP
      directives:
        description: Install XnSoft.XnViewMP
        allowPrerelease: true
      settings:
        id: XnSoft.XnViewMP
        source: winget